-- No seed data needed for v3.
-- Gyms, admins, members, competitions and goals are all created through the app:
--   1. Go to /admin/signup to create your gym + first admin account.
--   2. Log in at /admin, create a competition and goals.
--   3. Members join at / using the gym code (or QR code).
